homeApp.config(function ($translateProvider) {
	  $translateProvider.translations('en', {
	    PROJECT_NAME:'Board Games: Exchange',
	    LOGIN: 'Login',
	    REGISTRATION: 'Registration',	    
	    CUR_RATING:'Your rating is {{rating}}',
	    NEEDED_RATING:'You need {{neededRating}} to achieve next level',
	    SEARCH:'Search',
	    WELCOME_BACK:'Welcome back, ',
	    EDIT_PROFILE:'Edit profile',
	    MESSAGES:'Messages',
	    USERS:'Users',
	    LOGOUT:'Logout',
	    ALL_GAMES:'All games',
	    EVENTS:'Events',
	    TOURNAMENTS:'Tournaments',
	    STATISTICS:'Statistics',
	    EDIT_PROFILE:'Edit profile',
	    USER_PROFILE:'User profile',
	    UPLOAD_AVATAR:'upload avatar',
	    FIRST_NAME:'First name:',
	    LAST_NAME:'Last name:',
	    USERNAME:'Username:',
	    EMAIL:'Email:',
	    COUNTRY:'Country:',
	    CITY:'City:',
	    GENDER:'Gender:',
	    AGE:'Age:',
	    PHONE_NUMBER:'Phone number:',
	    SAVE_BUTTON:'Save',
	    CHANGE_PASSWORD:'Change password',
	    OLD_PASSWORD:'Old password:',
	    NEW_PASSWORD:'New password:',
	    CONFIRM_PASSWORD:'Confirm password:',
	    SAVE_PASSWORD_BUTTON:'Save password',
	    USERS:'Users',
	    USER_LAST_NAME:'Last name: {{userLastName}}',
	    USER_FIRST_NAME:'First name: {{userFirstName}}',
	    USER_GENDER:'Gender: {{userGender}}',
	    USER_AGE:'Age: {{userAge}}',
	    USER_LEVEL:'Level: {{userLevel}}',
	    USER_PHONE_NUMBER:'Phone number: {{userPhoneNumber}}',
	    USER_GAMES:'Games user owns',
	    USER_TOURNAMENTS:'Users tournaments',
	    USERNAME_TABLE:'Username',
	    EMAIL_TABLE:'Email',
	    COUNTRY_TABLE:'Country',
	    CITY_TABLE:'City',
	    LOGINFORM_HEADER: 'LOGIN WITH USERNMAE AND PASSWORD',
	    LOGINFORM_USERNAME:'Enter Username',
	    LOGINFORM_PASSWORD:'Enter Password',
	    LOGINFORM_ENTER: 'START',
	    CANCEL: 'Cancel',
	    DONT_HAVE_ACCOUNT: 'Don\'t have an account? Click here!',
	    INCORRECT_LOGIN_OR_PASS:'INCORRECT LOGIN OR PASSWORD',
	    REGFORM_HEADER: 'REGISTRATION OF NEW USER',
	    REGFORM_USERNAME: 'Username',
	    REGFORM_FIRSTNAME: 'First Name',
	    REGFORM_LASTNAME: 'Last Name',
	    REGFORM_EMAIL: 'Email',
	    REGFORM_PASSWORD: 'Password',
	    REGFORM_CONFIRMPASSWORD: 'Confirm Password',
	    REGFORM_GENDER: 'Gender',
	    REGFORM_GENDER_MALE: 'Male',
	    REGFORM_GENDER_FEMALE: 'Female',
	    REGFORM_SIGNUP: 'Sign up',
	    REGFORM_USERNAME_PLACEHOLDER: 'Enter Your Username. From 3 to 15 symbols required',
	    REGFORM_FIRSTNAME_PLACEHOLDER: 'Enter Your Name',
	    REGFORM_LASTNAME_PLACEHOLDER: 'Enter Your Last Name',	
	    REGFORM_EMAIL_PLACEHOLDER: 'Enter Your email address',
	    REGFORM_PASSWORD_PLACEHOLDER: 'From 6 to 20 symbols. 1 Upper case and 1 number is required',
	    REGFORM_CONFIRMPASSWORD_PLACEHOLDER: 'Please, confirm Your password',
	  });
	  $translateProvider.translations('ua', {
		PROJECT_NAME:'Настільні ігри: Обмін',
		LOGIN: 'Логін',
		REGISTRATION: 'Реєстрація',
	    CUR_RATING:'Ваш рейтинг {{rating}}',
	    NEEDED_RATING:'Вам потрібно набрати {{neededRating}} для отримання наступного звання',
	    SEARCH:'Пошук',
	    WELCOME_BACK:'З поверненням,',
	    EDIT_PROFILE:'Редагувати профіль',
	    MESSAGES:'Листи',
	    USERS:'Користувачі',
	    LOGOUT:'Вийти',
	    ALL_GAMES:'Всі ігри',
	    EVENTS:'Події',
	    TOURNAMENTS:'Турніри',
	    STATISTICS:'Статистика',
	    EDIT_PROFILE:'Редагувати профіль',
	    USER_PROFILE:'Сторінка користувача',
	    UPLOAD_AVATAR:'завантажити аву',
	    FIRST_NAME:'Ім`я:',
	    LAST_NAME:'Прізвище:',
	    USERNAME:'Логін:',
	    EMAIL:'Електронна пошта:',
	    COUNTRY:'Країна:',
	    CITY:'Місто:',
	    GENDER:'Стать:',
	    AGE:'Вік:',
	    PHONE_NUMBER:'Телефон:',
	    SAVE_BUTTON:'Зберегти',
	    CHANGE_PASSWORD:'Змінити пароль',
	    OLD_PASSWORD:'Старий пароль:',
	    NEW_PASSWORD:'Новий пароль:',
	    CONFIRM_PASSWORD:'Підтвердити пароль:',
	    SAVE_PASSWORD_BUTTON:'Зберегти пароль',
	    USERS:'Користувачі',
	    USER_LAST_NAME:'Прізвище: {{userLastName}}',
	    USER_FIRST_NAME:'Ім`я: {{userFirstName}}',
	    USER_GENDER:'Стать: {{userGender}}',
	    USER_AGE:'Вік: {{userAge}}',
	    USER_LEVEL:'Звання: {{userLevel}}',
	    USER_PHONE_NUMBER:'Телефон: {{userPhoneNumber}}',
	    USER_GAMES:'Ігри користувача',
	    USER_TOURNAMENTS:'Турніри',
	    USERNAME_TABLE:'Логін',
	    EMAIL_TABLE:'Електронна пошта',
	    COUNTRY_TABLE:'Країна',
	    CITY_TABLE:'Місто',
	    LOGINFORM_HEADER: 'ВХІД ЗА ЛОГІНОМ ТА ПАРОЛЕМ',
	    LOGINFORM_USERNAME:'Введіть Ваш логін',
	    LOGINFORM_PASSWORD:'Введіть Ваш пароль',
	    LOGINFORM_ENTER: 'ВХІД',
	    CANCEL: 'Скасувати',
	    DONT_HAVE_ACCOUNT: 'Досі не зареєстровані? Вам сюди!',
	    INCORRECT_LOGIN_OR_PASS:'НЕВІРНИЙ ЛОГІН АБО ПАРОЛЬ',
	    REGFORM_HEADER: 'РЕЄСТРАЦІЯ НОВГО КОРИСТУВАЧА',
	    REGFORM_USERNAME: 'Логін',
	    REGFORM_FIRSTNAME: 'Ваше ім\'я',
	    REGFORM_LASTNAME: 'Ваше прізвище',
	    REGFORM_EMAIL: 'Пошта',
	    REGFORM_PASSWORD: 'Пароль',
	    REGFORM_CONFIRMPASSWORD: 'Підтвердіть пароль',
	    REGFORM_GENDER: 'Стать',
	    REGFORM_GENDER_MALE: 'Чоловік',
	    REGFORM_GENDER_FEMALE: 'Жінка',
	    REGFORM_SIGNUP: 'Реєстрація',
	    REGFORM_USERNAME_PLACEHOLDER: 'Введіть Ваш логін. Повинен містити від 3 до 15 символів',
	    REGFORM_FIRSTNAME_PLACEHOLDER: 'Введіть Ваше ім\'я',
	    REGFORM_LASTNAME_PLACEHOLDER: 'Введіть ваше прізвище',	
	    REGFORM_EMAIL_PLACEHOLDER: 'Введіть адресу вашої електронної скриньки',
	    REGFORM_PASSWORD_PLACEHOLDER: 'Від 6 до 20 символів. Хоча б 1 велика літера і 1 цифра',
	    REGFORM_CONFIRMPASSWORD_PLACEHOLDER: 'Підтрвердіть Ваш пароль, будь ласка',
	  });
	  $translateProvider.preferredLanguage('en');
	  $translateProvider.useSanitizeValueStrategy('escape');
	  $translateProvider.useCookieStorage();
});

homeApp.controller('localizationController', function($scope, $translate) {
	$scope.changeLanguage = function (key) {
	    $translate.use(key);
	};
});